version: "3"

services:
  server:
    build:
      context: ./server
    ports:
      - "9000:9000"

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
